apiVersion: v1
kind: Service
metadata:
 name: java-ms-services
 labels:
   app: java-ms

spec:
 type: NodePort
 ports:
  - port: 2222
    targetPort: 2222
    nodePort: 30005
 selector:
    app: java-ms