apiVersion: apps/v1
kind: Deployment
metadata:
 name: java-ms
 labels:
   app: java-ms
spec:
  replicas: 2
  selector:
   matchLabels:
     app: java-ms
  template: 
    metadata:
      labels: 
        app: java-ms
    spec:
     containers:
     - name: java-ms
       image: naga54/account-service
       ports:
       - containerPort: 2222
         protocol: TCP
     imagePullSecrets:
     - name: java 