apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  volumes:
   - name: pvc-devops
     persistentVolumeClaim:
      claimName: pvc-devops
  selector:
    matchLabels:
      app: nginx
    replicas:
    template:
      metadata:
       labels:
          app: nginx
       spec:
        containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80
          volumeMounts:
           - mountPath: "/usr/share/nginx/html"
             name: pvc-devops

